name: daily-breadth

on:
  schedule:
    - cron: '0 0 * * *'        # midnight UTC daily
  workflow_dispatch:

permissions:
  contents: write             # ensure the GITHUB_TOKEN has write permission

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout the repo, persisting GITHUB_TOKEN for pushes:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true   # <–– this makes sure git push uses $GITHUB_TOKEN
          fetch-depth: 0             # ensures full history if you need to amend commits

      # 2) Set up Python 3.11
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3) Install dependencies
      - name: Install dependencies
        run: pip install pandas requests ta

      # 4) Run the breadth‐generator script
      - name: Run breadth generator
        run: python generate_breadth.py

      # 5) Commit & push any changes to data/*.csv
      - name: Commit CSVs back to GitHub
        run: |
          git config user.name  "breadth-bot"
          git config user.email "breadth-bot@users.noreply.github.com"
          git add data/*.csv
          git commit -m "auto: daily breadth" || echo "No changes to commit"
          git push
