name: daily-breadth
on:
  schedule:
     - cron: '0 0 * * *'    # 00:00 UTC every day
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with: { python-version: '3.11' }
      - run: pip install pandas requests ta
      - run: python generate_breadth.py
      - run: |
          git config user.name  "breadth-bot"
          git config user.email "bot@users.noreply.github.com"
          git add data/*.csv
          git commit -m "auto: daily breadth" || echo "no changes"
          git push
