name: daily-breadth

on:
  schedule:
    - cron: '0 0 * * *'    # every midnight UTC
  workflow_dispatch:     # allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas ta python-dayjs

      - name: Generate breadth via CryptoCompare
        env:
          CRYPTOCOMPARE_API_KEY: ${{ secrets.CRYPTOCOMPARE_API_KEY }}
        run: |
          python generatebreadth.py

      - name: Preview first 5 lines of BR75.csv and BR200.csv
        run: |
          echo "===== data/BR75.csv ====="
          head -n5 data/BR75.csv || true
          echo "===== data/BR200.csv ====="
          head -n5 data/BR200.csv || true

      - name: Commit updated CSVs
        run: |
          git config user.name "breadth-bot"
          git config user.email "breadth-bot@example.com"
          git add data/BR75.csv data/BR200.csv
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -m "ci: nightly breadth update"
            git push
          fi
